name: free_tuber
description: A Flutter app that allows YouTube videos to be streamed like a music service.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  youtube_player_flutter: ^8.0.0
  http: ^1.1.0

  # A powerful Http client for Dart
  dio: ^4.0.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  sembast: ^3.1.0+2
  path_provider: ^2.0.2

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^2.0.6

  # for dependency injection
  get_it: ^7.1.3

  # XXTEA is a fast and secure encryption algorithm. This is a XXTEA library for Dart.
  xxtea: ^2.1.0

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^6.0.1

  # YoutubeExplode is a library that provides an interface to query metadata of YouTube
  youtube_explode_dart: ^2.0.2

#  # Audio & Video player in Flutter.
#  flutter_playout: ^2.0.1

  # A flexible widget for user notification. Customize your text, button, duration, animations
  # and much more. For Android devs, it is made to replace Snackbars and Toasts.
  another_flushbar: ^1.10.23

  # Icon
  eva_icons_flutter: ^3.0.2

  # Animations
  shimmer: ^2.0.0
  transparent_image: ^2.0.0

  # Text
  intl: ^0.18.1

  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3

  video_player: ^2.4.7
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.7
  audio_session: ^0.1.6+1
  iso_duration_parser: ^1.1.1
  tab_indicator_styler: ^2.0.0
  auto_orientation: ^2.2.1
  event_bus: ^2.0.0
  wakelock_plus: ^1.1.4
  flutter_svg: ^1.1.6
  dots_indicator: ^2.1.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.7
  launch_review: ^3.0.1
  locale_plus: ^1.5.0
  collection: ^1.17.2
  share_plus: ^7.2.1
  in_app_update: ^4.2.2
  iconsax: ^0.0.8
  in_app_review: ^2.0.8
  app_version_update: ^4.0.1
  device_info_plus: ^9.0.3
  permission_handler: ^10.2.0
  ionicons: ^0.2.1
  extractor: ^0.0.3
  soundcloud_explode_dart: ^1.0.0
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.1+3
  build_runner: ^2.2.0
  analyzer: 4.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700